```{r}
#install necessary packages
#install.packages("BiocManager")
#BiocManager::install("EBImage")
#install.packages("tensorflow")
```
```{r}
#import the libraries
library(keras)
library(EBImage)
library(tensorflow)
#install_tensorflow(package_url = "https://pypi.python.org/packages/b8/d6/af3d52dd52150ec4a6ceb7788bfeb2f62ecb6aa2d1172211c4db39b349a2/tensorflow-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl#md5=1cf77a2360ae2e38dd3578618eacc03b")

```

```{r}
#Reading all images
pics <- c("c1.jpg", "c2.JPG", "c3.JPG", "c4.JPG", "c5.jpg", "c6.jpg",
          "p1.jpg","p2.jpg", "p3.jpg", "p4.jpg", "p5.jpg", "p6.jpg")
```


```{r}
#Storing images into a list
myimage <- list()
for (i in 1:12) {
  myimage[[i]] <- readImage(pics[i])
}
print(myimage[[1]])
display(myimage[[i]])  #Sample view
```


```{r}
#Re-sizing the images
for (i in 1:12){
  myimage[[i]] <- resize(myimage[[i]],28,28)
}

#To check structure of all images
str(myimage)
```


```{r}
#Re-shaping the images
for (i in 1:12){
  myimage[[i]] <- array_reshape(myimage[[i]], c(28,28,3))
}

display(myimage[[8]])
```

```{r}
display(myimage[[3]])

#Splitting the data to train and test
train <- NULL
for(i in 1:5){  #Loading first 5 plane images
  train <- rbind(train, myimage[[i]])
}

for(i in 7:11){  #loading first 5 car images
  train <- rbind(train, myimage[[i]])
}
print("Dimension of Train data : ")
dim(train)

test <- rbind(myimage[[6]],myimage[[12]])
print("Dimension of Test data : ")
dim(test)
```


```{r}
#Encoding the labels
train_labels <- c(1,1,1,1,1,0,0,0,0,0)
test_labels <- c(1,0)

#converting to categorical (One-hot encoding)
train_labels <- to_categorical(train_labels)
test_labels <- to_categorical(test_labels)

print("Train data labels")
train_labels
print("Test data labels")
test_labels
```

```{r}
#building a neural network model by adding layers
#1st layer has 256 units and uses relu function
#2nd layer has 128 units and uses relu function
#3rd- output layer has 2 units for 2 possible outputs and uses softmax
model <- keras_model_sequential()  #using sequential model
model %>%
  layer_dense(units = 256, activation = "relu",input_shape = c(2352))%>%
  layer_dense(units = 128, activation = "relu")%>% 
  layer_dense(units = 2, activation = "softmax")
summary(model)
```

```{r}
#Training the model on 30 epochs

model%>%
  compile(loss = "binary_crossentropy",
          optimizer = optimizer_rmsprop(),
          metrics = c("accuracy"))
history <- model%>%
  fit(train, train_labels,
      epochs= 30,
      batch_size= 32,
      validation_split = .2)
```
```{r}
#Testing the model
model%>%
  evaluate(test, test_labels)
```

```{r}
#predicting on train data
pred_train<- model%>%
  predict_classes(train)
pred_train
```

```{r}
#predicting on Test data
pred_test<- model%>%
  predict_classes(test)
pred_test

```

```{r}
#Testing model with random images
test_img <- c("Random_images/test_car3.jpg")  #Loading a random test image from web
test_random <-list()
test_random[[1]] <- readImage(test_img[1])

test_random[[1]] <- resize(test_random[[1]],28,28)
test_random[[1]] <- array_reshape(test_random[[1]], c(28,28,3))

random_test <- rbind(test_random[[1]])

result<- model %>%
  predict_classes(random_test)
if(result== 1){
  print("Given image is a Car!")
}else{
  print("Given image is an Aeroplane!")
}
```


